### ISSUE TITLE
playbook root login problem

### ISSUE THREAD

**Issue by jamesooo** [jruels/AnsiblePlaybooks#1]
the site.yml file should use "sudo: yes" instead of "root: yes" as most centos vms will block root ssh by default.  also you should add "
- name: upgrade all packages
  yum: name=\* state=latest
- name: install selinux bindings 
  yum: name=libselinux-python state=present 
  " to the top of common tasks to account for selinux. other than those 2 it works great with the vm "chef/centos-6.5"

**Comment by jruels** [comment]
Thanks for the feedback.  Which specific playbook did you use?

**Comment by jamesooo** [comment]
oh haha right used the ansible-magento-lemp playbook

**Comment by jruels** [comment]
I'm not sure I want to update all packages on the server. That seems like it could cause problems.  

Will pulling in specific selinux packages be enough? If so, which packages are required?

**Comment by jamesooo** [comment]
it wouldn't let me yum anything without updating. it may be enough to simply update of yum itself, though i didn't have anything to lose by doing an update all so i didn't test it.

**Comment by jruels** [comment]
Hello @jamesooo, 
I've changed the default username to be centos and use sudo by default. I also created a role to enable SELinux.

I didn't run into any issues installing packages so I'm not going to update all packages by default.   

Please test out and let me know if you see any other problems.
